### ISSUE TITLE
hfst and lttoolbox transducers behave differently

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-yid#2]
The HFST transducer is operating as expected:
```
$ echo "דער" | hfst-proc yid.automorf.hfst 
^דער/די<det><f><dat>/דער<det><m><nom>$
```

The lttoolbox transducer, which is derived directly from the HFST transducer, appears to be missing a lot of things:
```
$ echo "דער" | lt-proc yid.automorf.bin
^דער/*דער$
```

I tried the [hfst-minimise trick](https://wikis.swarthmore.edu/ling073/Hfst-minimise_trick) to no apparent avail.

Any thoughts on this issue, @flammie or @ftyers ?

**Comment by ftyers** [comment]
This is probably related to:

* https://github.com/apertium/lttoolbox/issues/9

Does the `yid.automorf.hfst` start with an epsilon transition? It's probably an issue in the ATT compiler.
